# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib fabricQueryR, .registration = TRUE
NULL

#' Read a Delta table through delta-rs and write Arrow IPC output.
#' @keywords internal
#' @noRd
fabric_delta_rs_read_to_ipc <- function(
  uri,
  bearer_token,
  version,
  columns,
  limit,
  ipc_path
) {
  .Call(
    wrap__fabric_delta_rs_read_to_ipc,
    uri,
    bearer_token,
    version,
    columns,
    limit,
    ipc_path
  )
}

# nolint end
